### PR TITLE
Mark libarchive as required so CMake errors out if not found

### PR DESCRIPTION
**Pull request by ericriff**
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [X] Build-related changes
- [ ] Other, please describe:

**Describe your Pull Request:**
libarchive is not an optional dependency so it must be marked as such. This ensures cmake errors out on `find_package` instead of further down the line while trying to link.

### CODE REVIEW

**Comment by ericriff** [comment]
Do you mind tagging this change so I can update the conan package to support 2.2.x with no patches? Otherwise I'd have to include this as a patch

**Comment by antony-jr** [comment]
Sure, there is still a PR left which will not take a long time to get merged, once that's merged, I will make a new release.

**Comment by ericriff** [comment]
Awesome, thanks.

**Comment by ericriff** [comment]
Kind reminder :)

**Pull request merged**
