### PR TITLE
add utf8 tests

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
hrm. wonder why this doesn't fail.

**Comment by antony-jr** [comment]
Because you are not running the new test? you need to add a new method inside the test class, first in the disk compression to create the archive and then in disk extractor to test if we can get what we put in, without any changes. Also we need to do it in msvc if we want the real windows test, MSVC does a lot of weird things.

**Comment by antony-jr** [comment]
This should do the trick,
```
diff --git a/tests/QArchiveDiskCompressorTests.cc b/tests/QArchiveDiskCompressorTests.cc
index c6dc700..6dd87b1 100644
--- a/tests/QArchiveDiskCompressorTests.cc
+++ b/tests/QArchiveDiskCompressorTests.cc
@@ -13,6 +13,7 @@ void QArchiveDiskCompressorTests::initTestCase() {
   dir.mkpath(TestCase6OutputDir);
   dir.mkpath(TestCase7OutputDir);
   dir.mkpath(TestCase8OutputDir);
+  dir.mkpath(TestCase9OutputDir);
 }
 
 void QArchiveDiskCompressorTests::simpleCompression() {
@@ -231,6 +232,30 @@ void QArchiveDiskCompressorTests::compressEmptyFiles() {
   QVERIFY(QFileInfo::exists(TestCase8ArchivePath));
 }
 
+void QArchiveDiskCompressorTests::compressingSpecialCharacterFiles() {
+  QArchive::DiskCompressor e(TestCase9ArchivePath);
+
+  /* Write the file to compress and add it. */
+  QFile TestOutput(TemporaryFilePath);
+  QVERIFY((TestOutput.open(QIODevice::WriteOnly)) == true);
+  TestOutput.write(Test9OutputContents.toLatin1());
+  TestOutput.close();
+
+  e.addFiles(/*entry name(optional)=*/QFileInfo(Test9OutputFile).fileName(),
+             TemporaryFilePath);
+
+  QObject::connect(&e, &QArchive::DiskCompressor::error, this,
+                   &QArchiveDiskCompressorTests::defaultErrorHandler);
+  QSignalSpy spyInfo(&e, SIGNAL(finished()));
+  e.start();
+
+  /*  Must emit exactly one signal. */
+  QVERIFY(spyInfo.wait() || spyInfo.count());
+
+  /* The archive should also exists. */
+  QVERIFY(QFileInfo::exists(TestCase9ArchivePath));
+}
+
 void QArchiveDiskCompressorTests::defaultErrorHandler(short code,
                                                       const QString& file) {
   auto scode = QString::number(code);
diff --git a/tests/QArchiveDiskCompressorTests.hpp b/tests/QArchiveDiskCompressorTests.hpp
index 3646e55..ceecc2b 100644
--- a/tests/QArchiveDiskCompressorTests.hpp
+++ b/tests/QArchiveDiskCompressorTests.hpp
@@ -28,6 +28,7 @@ class QArchiveDiskCompressorTests : public QObject, private QArchiveTestCases {
   void compressingTarArchiveWithoutFilters();
   void compressingTarArchiveWithZSTD();
   void compressEmptyFiles();
+  void compressingSpecialCharacterFiles();
 
  protected slots:
   static void defaultErrorHandler(short code, const QString& file);
diff --git a/tests/QArchiveDiskExtractorTests.cc b/tests/QArchiveDiskExtractorTests.cc
index 4571b24..371d4a3 100644
--- a/tests/QArchiveDiskExtractorTests.cc
+++ b/tests/QArchiveDiskExtractorTests.cc
@@ -9,12 +9,13 @@ void QArchiveDiskExtractorTests::initTestCase() {
           QFileInfo(TestCase4ArchivePath).exists() &&
           QFileInfo(TestCase5ArchivePath).exists() &&
           QFileInfo(TestCase6ArchivePath).exists() &&
-          QFileInfo(TestCase7ArchivePath).exists())) {
+          QFileInfo(TestCase7ArchivePath).exists() &&
+         QFileInfo(TestCase8ArchivePath).exists() &&
+         QFileInfo(TestCase9ArchivePath).exists())) {
       QFAIL("cannot find test case files.");
       return;
     }
   } else {
-
     QFAIL("cannnot find test cases.");
   }
 }
@@ -228,6 +229,22 @@ void QArchiveDiskExtractorTests::extractTarArchiveWithZSTD() {
   TestOutput.close();
 }
 
+void QArchiveDiskExtractorTests::extractSpecialCharacterFiles() {
+  QArchive::DiskExtractor e(TestCase9ArchivePath, TestCase9OutputDir);
+  QObject::connect(&e, &QArchive::DiskExtractor::error, this,
+                   &QArchiveDiskExtractorTests::defaultErrorHandler);
+
+  QFile TestOutput;
+  QSignalSpy spyInfo(&e, SIGNAL(finished()));
+  e.start();
+
+  QVERIFY(spyInfo.wait() || spyInfo.count() == 1);
+  TestOutput.setFileName(Test9OutputFile);
+  QVERIFY((TestOutput.open(QIODevice::ReadOnly)) == true);
+  QVERIFY(Test9OutputContents == QString(TestOutput.readAll()));
+  TestOutput.close();
+}
+
 void QArchiveDiskExtractorTests::isExtractorObjectReuseable() {
   QArchive::DiskExtractor e(TestCase5ArchivePath, TestCase5OutputDir);
   QObject::connect(&e, &QArchive::DiskExtractor::error, this,
diff --git a/tests/QArchiveDiskExtractorTests.hpp b/tests/QArchiveDiskExtractorTests.hpp
index 2a3feb9..7fe60b7 100644
--- a/tests/QArchiveDiskExtractorTests.hpp
+++ b/tests/QArchiveDiskExtractorTests.hpp
@@ -29,6 +29,7 @@ class QArchiveDiskExtractorTests : public QObject, private QArchiveTestCases {
   void getInfoFromTarArchiveWithNoFilters();
   void extractTarArchiveWithNoFilters();
   void extractTarArchiveWithZSTD();
+  void extractSpecialCharacterFiles();
   void isExtractorObjectReuseable();
   void testProgress();
  protected slots:
diff --git a/tests/QArchiveTestCases.hpp b/tests/QArchiveTestCases.hpp
index d639160..bff45cc 100644
--- a/tests/QArchiveTestCases.hpp
+++ b/tests/QArchiveTestCases.hpp
@@ -53,6 +53,10 @@ class QArchiveTestCases {
     TestCase8ArchivePath = TestCasesDir + "Test8.zip";
     TestCase8OutputDir = TestOutputDir + "Test8";
     Test8OutputFile = TestCase8OutputDir + "/Test8SpecialEmptyFile.txt";
+    
+    TestCase9ArchivePath = TestCasesDir + "Test9.zip";
+    TestCase9OutputDir = TestOutputDir + "Test9";
+    Test9OutputFile = TestCase9OutputDir + "/新建文件.txt";
   }
 
   ~QArchiveTestCases() = default;
@@ -84,6 +88,9 @@ class QArchiveTestCases {
   QString TestCase8ArchivePath;
   QString TestCase8OutputDir;
   QString Test8OutputFile;
+  QString TestCase9ArchivePath;
+  QString TestCase9OutputDir;
+  QString Test9OutputFile;
   QString TemporaryFilePath;
 
  protected:
@@ -97,6 +104,7 @@ class QArchiveTestCases {
   const QString Test5OutputContents = "TEST5SUCCESS!";
   const QString Test6OutputContents = "TEST6SUCCESS!";
   const QString Test7OutputContents = "TEST7SUCCESS!";
+  const QString Test9OutputContents = "测试9成功!";
 };
 
 #endif  // QARCHIVE_TEST_CASES_HPP_INCLUDED
```

**Comment by antony-jr** [comment]
ironically, the test correctly fails in ubuntu but not windows.

**Comment by neheb** [comment]
hmmm? If test fails, why does CI not fail?

**Comment by antony-jr** [comment]
> hmmm? If test fails, why does CI not fail?

That's because we are not returning the return code from each test run and check them, see tests/TestRunner.cc and tests/main.cc to see that we never pass the return codes to the main function, might have to fix this in the future.

**Comment by antony-jr** [comment]
Sorry, I think this code is wrong, 

```
TestOutput.write(Test9OutputContents.toLatin1());
```

should be,

```
TestOutput.write(Test9OutputContents.toUtf8());
```

I think there was a PR which replaced all toUtf8 to toLatin1 (need to go back to utf8), I think it really messed up everything, the test will not fail in UNIX based OS.

**Comment by antony-jr** [comment]
After you add the previous patch, use the below patch to fail the CI/CD when a test fails,

```
diff --git a/tests/TestRunner.cc b/tests/TestRunner.cc
index e976b6e..bfb448e 100644
--- a/tests/TestRunner.cc
+++ b/tests/TestRunner.cc
@@ -5,12 +5,13 @@
 #include <TestRunner.hpp>
 
 TestRunner::TestRunner()
-    : m_CompressorTests(&m_TempDir),
+    : n_ReturnCode(0),
+      m_CompressorTests(&m_TempDir),
       m_MemoryCompressorTests(&m_TempDir),
       m_ExtractorTests(&m_TempDir),
       m_MemoryExtractorTests(&m_TempDir) {
-  connect(&m_FutureWatcher, &QFutureWatcher<void>::finished, this,
-          &TestRunner::finished, Qt::DirectConnection);
+  connect(&m_FutureWatcher, &QFutureWatcher<void>::finished,
+          [&]() { emit finished(n_ReturnCode); });
 }
 
 void TestRunner::start() {
@@ -24,14 +25,8 @@ void TestRunner::start() {
 void TestRunner::runTests() {
   // Run the compressor tests which should generate the
   // desired archives to test it with the extractor.
-  QTest::qExec(&m_CompressorTests);
-
-  // Run disk extractor tests.
-  QTest::qExec(&m_ExtractorTests);
-
-  // Run memory extractor tests
-  QTest::qExec(&m_MemoryExtractorTests);
-
-  // Run memory compressor tests
-  QTest::qExec(&m_MemoryCompressorTests);
+  n_ReturnCode = QTest::qExec(&m_CompressorTests) |
+                 QTest::qExec(&m_ExtractorTests) |
+                 QTest::qExec(&m_MemoryExtractorTests) |
+                 QTest::qExec(&m_MemoryCompressorTests);
 }
diff --git a/tests/TestRunner.hpp b/tests/TestRunner.hpp
index c6bbbeb..a28d028 100644
--- a/tests/TestRunner.hpp
+++ b/tests/TestRunner.hpp
@@ -19,9 +19,10 @@ class TestRunner : public QObject {
  private Q_SLOTS:
   void runTests();
  Q_SIGNALS:
-  void finished();
+  void finished(int);
 
  private:
+  int n_ReturnCode;
   QTemporaryDir m_TempDir;
   QFuture<void> m_Future;
   QFutureWatcher<void> m_FutureWatcher;
diff --git a/tests/main.cc b/tests/main.cc
index 7c89f60..3463c0f 100644
--- a/tests/main.cc
+++ b/tests/main.cc
@@ -5,7 +5,7 @@ int main(int ac, char** av) {
   QCoreApplication app(ac, av);
   TestRunner TestRun;
   QObject::connect(&TestRun, &TestRunner::finished, &app,
-                   &QCoreApplication::quit);
+                   &QCoreApplication::exit);
   QTimer::singleShot(1000, &TestRun, SLOT(start()));
   return QCoreApplication::exec();
 }
```

**Comment by antony-jr** [comment]
I hope this will finish this PR, I have a fix in mind already.

**Pull request merged**
