### PR TITLE
Add libarchive lib&.h

### PR DESCRIPTION
**Pull request by alvin-xian**
add libarchive windows env
which build by msvc2013

**What kind of change does this pull request introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Describe your Pull Request:**
suport windows

### CODE REVIEW

**Comment by antony-jr** [comment]
@alvin-xian Its a bad idea to add binaries to git and will only bloat the repo. If possible I will upload this in github releases.

**Comment by antony-jr** [comment]
Also I think its wise to build a Qt plugin for QArchive(with libarchive statically linked to it) and automatically release the pre-built binary for Windows, Linux and other platforms on every version release.

**Comment by alvin-xian** [comment]
Ok，look forward to QArchive Plugin。 you are really doing a good job!

other ways， there are some thing wrong on windows platform:
1、while i use QArchive::DiskExtractor::setArchive(const QString &archivePath) to exract a tar.gz file, error had showed:  
> archive_read_open_QIODevice -30
> an error has occured :: ["QArchive::ArchiveReadError"]

2、while i try to extract 7z file， error had showed：

> An error has occured :: "QArchive::ArchiveCorrupted"

**Comment by antony-jr** [comment]
Does this error occur always? Could you upload a example archive to https://transfer.sh which cause such errors, I could really use them to test for errors. The thing is that the library will fail if **libarchive is not configured and built correctly**. So make sure you have installed libarchive with all the required libraries. That's why we really need a Qt plugin so Windows users or any other users don't have to suffer compiling libarchive from source.

**Comment by alvin-xian** [comment]
https://transfer.sh/10iihV/QArchiveDemo.7z
it run on windows7 by qt5.7.1 msvc2013

**Comment by antony-jr** [comment]
> https://transfer.sh/10iihV/QArchiveDemo.7z
it run on windows7 by qt5.7.1 msvc2013

@alvin-xian Never mind, It seems that the **error only exists in windows** and I suspect its due to compilation of libarchive without proper support for 7z and tar. Did you compile libarchive with the following required **optional** libs -> zlib, liblzma, bz2lib, liblz4, libzstd. I think for now libarchive works properly if you compile with cgywin.

And you need **liblzma** for 7z support. 


**Anyways I will try to compile the entire library in Windows and test everything to confirm this.**

**Comment by alvin-xian** [comment]
@antony-jr Yes, I compile libarchive without zlib/liblzma..., but it works while i tar files use `QArchive::TarFormat`
I will try to compile libarchive again.

**Comment by unusual-aspect** [comment]
@alvin-xian do you build libarchive using qmake? or cmake? 
As nice feature will be to get *.pro file that we can include with QArchive :)

**Comment by antony-jr** [comment]
> @alvin-xian do you build libarchive using qmake? or cmake?
> As nice feature will be to get *.pro file that we can include with QArchive :)

@unusual-aspect can you please elaborate? I don't get you. 

**Side Note:** It's been a year since I planned to release pre-built QArchive qt plugins with libarchive statically linked with it. But I'm still at zero progress. The first task would be to create a plugin interface to pack all the classes into a single interface which is where I'm stuck right now.

**Comment by unusual-aspect** [comment]
@antony-jr - finaly i found some time to have look of this issue

https://github.com/unusual-aspect/QArchiveBuild

Idea is to use VCPKG and install libarchive - then when we have libarchive installed, build QArchive, and last ins build application.

Similar idea will be for Linux/OSX - not tested yet, as i was working on Windows - but if you will find a time to have look over my git repo, you will sort this thing out ;)

**Comment by antony-jr** [comment]
> https://github.com/unusual-aspect/QArchiveBuild
>
> Idea is to use VCPKG and install libarchive - then when we have libarchive installed, build QArchive, and last ins build application.

Nice. I don't use Windows, So I have no idea how things are done in Windows. So it would have been painful for me to figure everything out.

> Similar idea will be for Linux/OSX - not tested yet, as i was working on Windows - but if you will find a time to have look over my git repo, you will sort this thing out ;)

Most Linux distros have libarchive in the package manager so I think it will be very easy on the linux side.

> That will sort problem with binaries in git (so we are not keep them, we use source!) - as with Qt Plugin, don't think is a issue here, as long we have option to use 'library' (and build from code) - there no problem with that.

I just want to release the pre-built binaries in github releases. As with Qt Plugin, we only have one dll to download for the user and can just use it with python + Qt or any other language with Qt. Qt Plugins can be released in github releases on each version release.

**Comment by antony-jr** [comment]
Now there is a conan package for QArchive https://conan.io/center/qarchive which provides prebuilt binaries for Windows, Linux and MacOS which is neat.

**Pull request closed without merging**
