### PR TITLE
QScopedPointer removals

### PR DESCRIPTION
**Pull request by neheb**
- [x] Refactor

Not sure if the m_Files change is correct.

### CODE REVIEW

**Comment by neheb** [comment]
Maybe better now, not sure.

**Comment by neheb** [comment]
Removed draft.

**Comment by neheb** [comment]
Reordered commits.

**Comment by antony-jr** [comment]
This looks good, move towards standard C++ is needed.

**Comment by neheb** [comment]
Is it? The only real changes I've done is to get rid of unique_ptr as Qt6 warns on QScopedPointer. The latter seems fishy as it has no move operations. Googling indicates it some compatibility thing with C++98.

**Comment by antony-jr** [comment]
> Is it? The only real changes I've done is to get rid of unique_ptr as Qt6 warns on QScopedPointer. The latter seems fishy as it has no move operations. Googling indicates it's some compatibility thing with C++98.

Yeah, that's what Qt also recommends, Qt created a lot of ways to manage memory and we can get lost with choosing which ones to use so it's best to use standard C++ for memory management to make this choices sane.

LGTM :+1:, give me some time since there is a lot of changes to review. Thank you for your time.

**Comment by neheb** [comment]
Added commit for tests. They still pass.

**Comment by neheb** [comment]
You want this split up in multiple PRs?

**Pull request merged**
