### PR TITLE
some clang-tidy fixes

### PR DESCRIPTION
**Pull request by neheb**
- [x] Code style update

I think two of these change API/ABI. I can remove them if needed.

### CODE REVIEW

**Comment by antony-jr** [comment]
LGTM :+1: but a lot of changes so it might take some time to merge this.

**Review by antony-jr — COMMENTED** [review]
See the comment on https://github.com/antony-jr/QArchive/pull/64/commits/09ce7d5087ade95a4421cbb43bb58779316b2153 but https://github.com/antony-jr/QArchive/pull/64/commits/18fa343dc58d89556f2b7a66b08f0147b92bd0b3 (ABI break) is good.

**Comment by neheb** [comment]
Added two extra ones. ABI change as with the previous one.

**Comment by antony-jr** [comment]
> I don't see a comment on [09ce7d5](https://github.com/antony-jr/QArchive/commit/09ce7d5087ade95a4421cbb43bb58779316b2153). I'll remove it anyway.

Don't remove it. Let's have it.

**Comment by antony-jr** [comment]
Okay I will merge the changes now, we can improve it over time. Thanks for this huge refactor. :+1:

**Pull request merged**
