### PR TITLE
github: run macOS tests with meson

### PR DESCRIPTION
**Pull request by neheb**
Since the meson wrap is available, we don't need to work around Homebrew bugs with libarchive.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

- [x] Build-related changes

### CODE REVIEW

**Comment by neheb** [comment]
```
2022-12-19T21:08:50.3299500Z QWARN  : QArchiveMemoryCompressorTests::simpleCompression() QMetaMethod::invoke: Unable to handle unregistered datatype 'QIODevice*'
2022-12-19T21:08:50.3300020Z FAIL!  : QArchiveMemoryCompressorTests::simpleCompression() "error:::: QArchive::NoFilesToCompress"
2022-12-19T21:08:50.3300450Z    Loc: [../tests/QArchiveMemoryCompressorTests.cc(415)]
2022-12-19T21:08:55.6020700Z FAIL!  : QArchiveMemoryCompressorTests::simpleCompression() 'spyInfo.wait() || spyInfo.count()' returned FALSE. ()
2022-12-19T21:08:55.6021950Z    Loc: [../tests/QArchiveMemoryCompressorTests.cc(20)]
2022-12-19T21:08:55.6022630Z QWARN  : QArchiveMemoryCompressorTests::usingPauseResume() QMetaMethod::invoke: Unable to handle unregistered datatype 'QIODevice*'
2022-12-19T21:08:55.6023430Z FAIL!  : QArchiveMemoryCompressorTests::usingPauseResume() "error:::: QArchive::NoFilesToCompress"
2022-12-19T21:08:55.6023880Z    Loc: [../tests/QArchiveMemoryCompressorTests.cc(415)]
2022-12-19T21:09:00.6438500Z FAIL!  : QArchiveMemoryCompressorTests::usingPauseResume() 'spyInfo.wait() || spyInfo.count()' returned FALSE. ()
2022-12-19T21:09:00.6440770Z    Loc: [../tests/QArchiveMemoryCompressorTests.cc(82)]
```

Hmmmmmmmmmmmm.

**Comment by neheb** [comment]
That error shows up with -Ddefault_library=shared -Dqt6=enabled . Interesting that it doesn't cause a failure...

**Comment by neheb** [comment]
well that didn't fix it...

**Comment by antony-jr** [comment]
> macOS needs qRegisterMetaType<QIODevice*>(); ???

No I don't think so, up until now, using CMake for test on MacOS, never seen these errors. Maybe we forgot to run moc on some source files, that could cause these issues like this.

**Comment by neheb** [comment]
AFAIK the only files ran through moc are ones with Q_OBJECT.

**Comment by antony-jr** [comment]
> AFAIK the only files ran through moc are ones with Q_OBJECT.

This includes the test source files too right? since the error is from building the tests.

**Comment by antony-jr** [comment]
But meson build works flawless on my linux box.

**Comment by neheb** [comment]
Yep: https://github.com/antony-jr/QArchive/blob/master/meson.build#L105

macOS with qt5 works fine. It's just qt6. Maybe it's a difference in the source. This PR changes the qt source from a 3rd party action to homebrew's qt.

**Comment by neheb** [comment]
Rebased.

Anyway, https://doc.qt.io/qt-6/qmetamethod.html#invoke says qRegisterMetaType is needed.

**Comment by antony-jr** [comment]
> Anyway, https://doc.qt.io/qt-6/qmetamethod.html#invoke says qRegisterMetaType is needed.

We don't really need to register Qt types, and ```QIODevice*``` is inherited from ```QObject*``` which is already registered
with the meta type system. Maybe this is because we are using brew's qt version and not GH action's qt6. Maybe brew qt6 formula might be doing something wrong. Maybe we need to have QObject* in the private class maybe? to solve this.

**We really don't want to register custom types, it's a lot of maintenance.**

Screenshot 2022-12-20 at 17-06-23 QMetaType Class Qt Core 6 4 1

Ref: https://doc.qt.io/qt-6/qmetatype.html

**Comment by neheb** [comment]
What do you mean QObject* in the private class?

**Comment by antony-jr** [comment]
Seems ok, but we still don't know why this is the case. Qt5 builds just fine but Qt6 fails on MacOS. And Linux just builds everything just fine. This is very weird. Regardless, I think this is fine for now.

**Comment by neheb** [comment]
Maybe some compiler bug with Apple's clang (not the same as LLVM clang).

**Comment by antony-jr** [comment]
> Maybe some compiler bug with Apple's clang (not the same as LLVM clang).

Maybe, but this change does not affect other builds hopefully. I will test this later on my MacOS VM.

**Pull request merged**
